version: '3.8'
services:
    db:
    image:mysql:5.7
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_DATABASE: ecoin_host
        MYSQL_ROOT_PASSWORD: root_password
    ports:
        - "3306:3306"
